name: SpleefSVG
main: me.waterman1001.SpleefSVG.Main
description: A simple SvestiGames Spleef plugin
author: Waterman1001
version: 1.0.0
api-version: 1.19
depend:
- WorldEdit

commands:
    spleef:
        description: Main spleef command. Go and play!

permissions:
    spleefsvg.command.*:
        description: Permissions to all of the /spleef sub commands
        default: false
        children:
            spleefsvg.commandlist: true
            spleefsvg.command.join: true
            spleefsvg.command.quit: true
            spleefsvg.command.forcestart: true
            spleefsvg.command.spectate: true
            spleefsvg.command.map.list: true
            spleefsvg.command.map.create: true
            spleefsvg.command.map.remove: true
            spleefsvg.command.map.setminy: true
            spleefsvg.command.map.setspawn: true
            spleefsvg.command.map.setloseloc: true
            spleefsvg.command.map.setwinloc: true
    spleefsvg.player:
         description: Permissions to all of the /spleef sub commands necessary for a player
         default: false
         children:
             spleefsvg.commandlist: true
             spleefsvg.command.join: true
             spleefsvg.command.quit: true
    spleefsvg.admin:
         description: Permissions to all of the /spleef sub commands necessary for an admin
         default: false
         children:
             spleefsvg.command.forcestart: true
             spleefsvg.command.spectate: true
             spleefsvg.command.map.list: true
             spleefsvg.command.map.create: true
             spleefsvg.command.map.remove: true
             spleefsvg.command.map.setminy: true
             spleefsvg.command.map.setspawn: true
             spleefsvg.command.map.setloseloc: true
             spleefsvg.command.map.setwinloc: true